# -*- coding: utf-8 -*-
"""fakeNewsDetector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xq6tSlWKh0Q4NZ2ex0KDYCXJDkJfR1S
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re
import string

# As your ML teacher, let's understand these crucial parameters for date conversion:

# When we use `pd.to_datetime(df['date'], format='mixed', errors='coerce')`:

# 1. `format='mixed'`:
#    - **What it does:** This tells pandas to try and infer the date and time format for *each individual string* in the 'date' column.
#    - **Why it's useful in ML:** Real-world data often comes from different sources or is entered inconsistently. You might have 'YYYY-MM-DD', 'MM/DD/YYYY', 'Month Day, Year', or 'DD-Mon-YY' all within the same column. Instead of you having to figure out every single format and write complex parsing logic, `format='mixed'` attempts to intelligently guess the correct format for each entry.
#    - **Think of it as:** A flexible detective that can recognize many different date patterns without explicit instructions for each one.

# 2. `errors='coerce'`:
#    - **What it does:** If pandas encounters a date string that it *cannot* parse (even with `format='mixed'`) into a valid datetime object, instead of raising an error and stopping the entire process, it will replace that unparseable entry with `NaT` (Not a Time).
#    - **Why it's useful in ML:** Data quality is rarely perfect. `errors='coerce'` allows your data pipeline to continue running even if there are a few bad date entries. These `NaT` values can then be handled using standard missing data techniques (e.g., dropping the rows, imputing, etc.), which is a common step in ML preprocessing.
#    - **Think of it as:** A robust error handler that gracefully manages malformed data, preventing your script from crashing and allowing you to deal with invalid data systematically later.

# **In summary, for ML:**
# Using `format='mixed'` and `errors='coerce'` together makes your date conversion highly resilient to diverse and imperfect date formats, which is a common challenge in data cleaning and feature engineering for machine learning models.

# Example of how we used it (from your notebook):
# df['date'] = pd.to_datetime(df['date'], format='mixed', errors='coerce')

df_fake = pd.read_csv('/content/Fake.csv', encoding='latin', engine='python', on_bad_lines='skip')
df_true = pd.read_csv('/content/True.csv', encoding='latin', engine='python', on_bad_lines='skip')
df_fake.head()

df_true.head()

df_fake.tail()

df_fake.info()

## firsty we have to convert date column in date type
df_fake['date'] = pd.to_datetime(df_fake['date'], format='mixed', errors='coerce')
df_true['date'] = pd.to_datetime(df_true['date'], format='mixed', errors='coerce')

df_fake.isnull().sum()

df_true.isnull().sum()

df_fake.shape

df_true.shape

"""## so we have to remove 10 rows from date column from 23k which is app. 0.04 % of whole data"""

blanks_rows=df_fake['text'].isna()
print(f'count of nan text rows:  {blanks_rows.sum()}')

"""## feature Engineering"""

# now we create a column "status"
#df_fake[status]='0' and df_true[status] = '1'

df_fake.insert(loc=4, column='status', value=0)
df_true.insert(loc=4, column='status', value=1)

df_fake.shape, df_true.shape

#
df_fake_manualTesting=df_fake.tail(10)
for i in range(10235,10225,-1):
  df_fake.drop([i],axis=0,inplace=True)

df_true_manualTesting=df_true.tail(10)
for i in range (12686,12676,-1):
  df_true.drop([i],axis=0,inplace=True)

df_fake.shape, df_true.shape

df_fake_manualTesting.head(10)

df_true_manualTesting.head(10)

df_manual_testing=pd.concat([df_fake_manualTesting,df_true_manualTesting],axis=0)
# df_manual_testing.head()
df_manual_testing.to_csv("manual_testing.csv")

"""##merge true and fake dataframe"""

df_merge=pd.concat([df_fake,df_true],axis=0)
df_merge.head()

df_merge.columns

"""#keep the main column and remove column that not needed"""

df_merge.drop(columns=['title','subject','date'],axis=1,inplace=True)

df_merge.isnull().sum()

"""#Random Sampling of dataframe"""

df=df_merge.sample(frac=1)
# df_merge.head()

df.head()

# reset index
df.reset_index(inplace=True)
df.drop(['index'],axis=1,inplace=True)

df.head()

"""#creating the function to process the text"""

def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub("\\W"," ",text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

df['text']=df['text'].apply(wordopt)

"""#dependent and independent variable"""

X=df['text']
y=df['status']

"""#training and testing split

the random =1 state is to reproduce the same split each time you run your program)
"""

x_train,x_test,ytrain,y_test=train_test_split(X,y,test_size=0.25,random_state=1)

"""#Convert text into vector"""

from sklearn.feature_extraction.text import TfidfVectorizer
vector=TfidfVectorizer()

xv_test=vector.fit_transform(x_test)
xv_train=vector.transform(x_train)

"""# build logistic regression model"""

from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()

lr.fit(xv_train , ytrain)

x_predict=lr.predict(xv_test)

lr.score(xv_test,y_test)

print(classification_report(x_predict,y_test))

"""#desicion  tree classification"""

from sklearn.tree import DecisionTreeClassifier

dt=DecisionTreeClassifier()

dt.fit(xv_train,ytrain)

pred_dt=dt.predict(xv_test)

dt.score(xv_test,y_test)

print(classification_report(pred_dt,y_test))

"""#Model Testing

"""

def output_label(n):
  if n==0:
    return "Fake News"
  elif n==1:
    return "True News"

def Testing(news):
  input_text={"text":[news]}
  df_test=pd.DataFrame(input_text)
  df_test['text']=df_test['text'].apply(wordopt)
  new_df_test=vector.transform(df_test['text'])
  pred_lr=lr.predict(new_df_test)
  pred_dt=dt.predict(new_df_test)

  return print(f'\n LR Prediction : {output_label(pred_lr[0])} \n DT Prediction : {output_label(pred_dt[0])}')

news= str(input())
Testing(news)

news= str(input())
Testing(news)